name: Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main  # Ganti jika pakai branch lain

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, ctype, json, tokenizer, fileinfo, openssl, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate application key
      run: php artisan key:generate

    - name: Run Laravel migrations (optional)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --force

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: PWL-POS # Ganti dengan nama App Service kamu
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
